#!/bin/bash

PATH_TO_CODE="./sources"

NAME="katrinTankViewer"
VERSION="0.0.1"

FILE_NAME_WITHOUT_VERSION=$NAME".js"
FILE_NAME_MIN=$NAME".min"-$VERSION".js"

PATH_TO_COMPILER="./utils/Closure-compiler/compiler.jar"

COMPILATION_LEVEL="WHITESPACE_ONLY"
# COMPILATION_LEVEL="SIMPLE_OPTIMIZATIONS"
# COMPILATION_LEVEL="ADVANCED_OPTIMIZATIONS"

python2.7 ./utils/generateCompresedFile.py "$PATH_TO_CODE" "$PATH_TO_COMPILER" "$COMPILATION_LEVEL" "$FILE_NAME_WITHOUT_VERSION"

echo "$FILE_NAME_WITHOUT_VERSION"

echo "$FILE_NAME_MIN"
cp "$FILE_NAME_WITHOUT_VERSION" ../"$FILE_NAME_MIN"